# Generated by Django 5.1.15 on 2026-09-01 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UpdateManifest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payload_type",
                    models.CharField(
                        choices=[
                            ("MODEL", "ONNX Model Update"),
                            ("MAP", "Map Package Update"),
                            ("SYSTEM_CONFIG", "System Config Update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_version", models.CharField(max_length=50)),
                ("artifact_url", models.CharField(max_length=500)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("file_size_bytes", models.BigIntegerField()),
                ("min_app_version", models.CharField(default="1.0.0", max_length=50)),
                (
                    "target_platform",
                    models.CharField(
                        choices=[
                            ("ANDROID", "Android"),
                            ("IOS", "iOS"),
                            ("ALL", "All"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                ("release_notes", models.TextField(blank=True)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
