# Generated by Django 5.1.15 on 2026-09-01 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("IDR_RECURRENT", "Recurrent Neural Network (LSTM/GRU)"),
                            ("IDR_TRANSFORMER", "Temporal Transformer"),
                            ("IDR_EKF_HYBRID", "Hybrid EKF + AI Model"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("semantic_version", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VALIDATING", "Validating"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active Deployment"),
                            ("DEPRECATED", "Deprecated"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("min_app_version", models.CharField(default="1.0.0", max_length=50)),
                (
                    "supported_platforms",
                    models.JSONField(default=list, help_text="['ANDROID', 'IOS']"),
                ),
                (
                    "sensor_profile_requirements",
                    models.JSONField(blank=True, default=dict),
                ),
                ("input_schema", models.JSONField(default=dict)),
                ("output_schema", models.JSONField(default=dict)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ml_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="models.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("ml_model", "semantic_version")},
            },
        ),
        migrations.CreateModel(
            name="ModelMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.FloatField()),
                (
                    "dataset_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="models.modelversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("format", models.CharField(default="ONNX", max_length=20)),
                ("file_path", models.FileField(upload_to="models/onnx/")),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("file_size_bytes", models.BigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact",
                        to="models.modelversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_platform",
                    models.CharField(
                        choices=[
                            ("ANDROID", "Android"),
                            ("IOS", "iOS"),
                            ("ALL", "All"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deployed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="models.modelversion",
                    ),
                ),
            ],
        ),
    ]
