# Generated by Django 5.1.15 on 2026-09-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="contract_spec",
            field=models.JSONField(
                blank=True, default=dict, help_text="Canonical contract schema spec"
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="opset_version",
            field=models.IntegerField(default=14, help_text="ONNX Opset version"),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="preprocessing_spec",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Preprocessing steps from contracts/model/preprocessing.json",
            ),
        ),
    ]
