# Generated by Django 5.1.15 on 2026-09-01 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetrySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("total_points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_sessions",
                        to="devices.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelemetryBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("sequence_number", models.IntegerField(default=1)),
                ("point_count", models.IntegerField(default=0)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_batches",
                        to="devices.device",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="telemetry.telemetrysession",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="TelemetryPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField(default=0.0)),
                ("velocity", models.FloatField(default=0.0)),
                ("heading", models.FloatField(default=0.0)),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "navigation_mode",
                    models.CharField(
                        choices=[
                            ("GNSS", "GNSS Only"),
                            ("INS_ONLY", "INS Only"),
                            ("AI_IDR_FUSED", "AI IDR Fused"),
                            ("MAP_MATCHED", "Map Matched"),
                            ("DEGRADED", "Degraded"),
                        ],
                        default="AI_IDR_FUSED",
                        max_length=30,
                    ),
                ),
                (
                    "gnss_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("DEGRADED", "Degraded"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="AVAILABLE",
                        max_length=30,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "map_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="telemetry.telemetrybatch",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="telemetry.telemetrysession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "timestamp"],
                        name="telemetry_t_session_60d5fe_idx",
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="telemetry_t_latitud_77e2bf_idx",
                    ),
                ],
            },
        ),
    ]
