# Generated by Django 5.1.15 on 2026-09-01 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_key",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ANDROID", "Android"), ("IOS", "iOS")], max_length=20
                    ),
                ),
                ("device_model", models.CharField(max_length=100)),
                ("os_version", models.CharField(max_length=50)),
                ("app_version", models.CharField(max_length=50)),
                ("imu_capabilities", models.JSONField(blank=True, default=dict)),
                ("sensor_capabilities", models.JSONField(blank=True, default=dict)),
                (
                    "active_model_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "active_map_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-registered_at"],
                "indexes": [
                    models.Index(
                        fields=["platform", "status"],
                        name="devices_dev_platfor_e8537a_idx",
                    ),
                    models.Index(
                        fields=["last_seen_at"], name="devices_dev_last_se_c75af6_idx"
                    ),
                ],
            },
        ),
    ]
