# Generated by Django 5.1.15 on 2026-09-01 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MapRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("country_code", models.CharField(default="IND", max_length=10)),
                (
                    "bounding_box",
                    models.JSONField(
                        default=dict,
                        help_text="{'min_lat', 'max_lat', 'min_lng', 'max_lng'}",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MapPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("region_code", models.CharField(db_index=True, max_length=50)),
                ("version", models.CharField(max_length=50)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("file_size_bytes", models.BigIntegerField()),
                ("file_path", models.FileField(upload_to="maps/packages/")),
                ("min_latitude", models.FloatField()),
                ("max_latitude", models.FloatField()),
                ("min_longitude", models.FloatField()),
                ("max_longitude", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "compatibility_min_app_version",
                    models.CharField(default="1.0.0", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("region_code", "version")},
            },
        ),
    ]
